version: '3.8'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gcube
      MYSQL_USER: gcube
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - gcube-network
    restart: unless-stopped
    ports:
      - '12101:3306'
  app:
    image: gcube-docker
    container_name: gcube-app-prod
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: deploy
    ports:
      - '${DOCKER_COMPOSE_PORT:-3000}:3000'
    networks:
      - gcube-network
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      - db
    stdin_open: true # docker run -i
    tty: true  

networks:
  gcube-network:
    driver: bridge
